### ISSUE TITLE
Add square wave generator to alarm project

### ISSUE THREAD

**Issue by GenteiJanken** [HERCsMusicSystems/va_pack#3]
At present the alarm application only receives MIDI events. The next step will be to add a square wave output, with amplitude varying between -0.2 and 0.2, and frequency determined by the MIDI event received. 

- [x]  Install libgtk2.0-dev locally and test system with VonForman and oscilloscope

**Comment by HERCsMusicSystems** [comment]
- [ ] Obtain the Sampling Frequency from JACK.

- [ ] The amplitude will come from MIDI event.

- [ ] The key number coming from MIDI event will need to be used to calculate TIME step.

**Comment by GenteiJanken** [comment]
Although my code needs some cleanup, I have reached the milestone of getting a tone from a given key and what sounded like its octave from the corresponding key in the next octave! In addition to aural confirmation, I see that `oscilloscope` shows the intended square wave. However, my development environment might not currently be up to task. Although the values should all be correct, the notes produced are off by several semitones (though consistently off, hence I could still hear octaves). This was also the case when playing the same notes through the `VonForman` synth, so I'm thinking it's a sound card driver problem in the VM rather than an application problem. Will clean up and double-check soon, then I'll push.

**Comment by GenteiJanken** [comment]
Huh, looks like dragging the ticket to Done doesn't close the issue. In any case this issue as specified has been completed.
